#!/usr/bin/env python3
"""Build the canonical agent and skill registries (single source of truth).

Emits:
  system-building-os/registries/agents.json
  system-building-os/registries/skills.json

Each entry carries the full semantic-adapter contract (see
system-building-os/contracts/semantic-adapter.md). The adapter generators read
these registries to project Claude and Codex runtime adapters.

Re-run to regenerate the registries. Edit the data tables below to change the OS.
"""
from __future__ import annotations

import json
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "system-building-os", "registries")

VERSION = "1.1.0"

# ---------------------------------------------------------------------------
# AGENTS  (id, scope, name, model_profile, purpose, responsibilities[],
#          required_skills[], file_ownership_hint)
# ---------------------------------------------------------------------------
AGENTS = [
 ("planning-orchestrator", "planning", "Planning Orchestrator", "highest_reasoning",
  "Owns the complete /plan_max process end to end.",
  ["maintain planning state", "invoke relevant planning agents",
   "prevent skipped dimensions", "synthesize outputs", "resolve conflicts",
   "maintain traceability", "ensure no implementation starts",
   "produce the final Codex package"],
  ["plan-max-orchestration", "requirement-completeness-audit", "decision-resolution",
   "cross-layer-reconciliation", "implementation-deliverables-planning",
   "production-readiness-planning"],
  ["plans/active/<slug>/**"]),
 ("grill-master", "planning", "Grill Master", "highest_reasoning",
  "Mandatory adversarial reviewer for every planning request.",
  ["challenge assumptions", "detect shallow thinking", "detect missing requirements",
   "detect contradictions", "identify overengineering", "identify oversimplification",
   "identify user-adoption risks", "identify implementation ambiguity",
   "challenge AI-vs-deterministic responsibility", "produce high-value questions"],
  ["grill-me-planning", "product-logic-and-intelligence-grill"], []),
 ("product-requirements-architect", "planning", "Product Requirements Architect", "balanced_reasoning",
  "Owns product scope, goals, users, journeys, requirements, business rules, acceptance criteria.",
  ["product scope", "goals", "users", "journeys", "requirements", "business rules",
   "acceptance criteria"],
  ["product-discovery", "requirement-extraction", "user-flow-planning",
   "business-rule-specification"],
  ["plans/active/<slug>/05-product-system-plan.md"]),
 ("system-architect", "planning", "System Architect", "highest_reasoning",
  "Owns system boundaries, components, interfaces, scalability, technical trade-offs, ADRs.",
  ["system boundaries", "components", "architecture", "interfaces", "scalability",
   "technical trade-offs", "architectural decisions"],
  ["technical-architecture-planning"],
  ["plans/active/<slug>/06-technical-architecture.md"]),
 ("data-architect", "planning", "Data Architect", "highest_reasoning",
  "Owns the data model, storage selection, entities, migrations, retention, reporting.",
  ["data model", "storage selection", "entities", "relationships", "indexes",
   "constraints", "multi-tenancy", "migrations", "retention", "backup", "reporting",
   "vector needs"],
  ["data-architecture-planning", "database-selection", "migration-planning"],
  ["plans/active/<slug>/07-data-architecture.md", "plans/active/<slug>/data-model.yaml"]),
 ("auth-security-architect", "planning", "Auth & Security Architect", "highest_reasoning",
  "Owns identity, roles, permissions, sessions, isolation, threats, secret boundaries.",
  ["identity", "roles", "permissions", "sessions", "organization isolation",
   "threats", "secret boundaries", "security acceptance criteria"],
  ["auth-authorization-planning", "security-threat-model-planning"],
  ["plans/active/<slug>/08-auth-security-plan.md"]),
 ("backend-api-architect", "planning", "Backend & API Architect", "balanced_reasoning",
  "Owns backend modules, domain services, APIs, events, jobs, queues, failure handling.",
  ["backend modules", "domain services", "APIs", "events", "jobs", "queues",
   "validation", "failure handling"],
  ["backend-api-planning"],
  ["plans/active/<slug>/10-backend-api-plan.md"]),
 ("frontend-uiux-architect", "planning", "Frontend & UI/UX Architect", "balanced_reasoning",
  "Owns screens, components, navigation, responsiveness, accessibility, hierarchy, motion, states.",
  ["screens", "components", "navigation", "responsiveness", "accessibility",
   "hierarchy", "alignment", "typography", "motion", "loading", "errors",
   "empty states", "perceived performance", "reference-package intake",
   "frontend experience grill", "screen + interaction contracts"],
  ["frontend-uiux-planning", "responsive-design-planning", "accessibility-planning",
   "motion-performance-planning", "frontend-reference-intake",
   "frontend-experience-grill", "frontend-screen-contract-planning",
   "frontend-backend-contract-planning"],
  ["plans/active/<slug>/09-frontend-uiux-plan.md",
   "plans/active/<slug>/frontend/**"]),
 ("ai-orchestration-architect", "planning", "AI Orchestration Architect", "highest_reasoning",
  "Owns AI responsibilities, prompts, tools, context, memory, output schemas, evaluation, safety.",
  ["AI responsibilities", "prompts", "tools", "context", "memory", "output schemas",
   "evaluation", "hallucination control", "AI safety", "AI cost and latency",
   "AI-vs-deterministic responsibility", "real provider integration path"],
  ["ai-flow-planning", "ai-evaluation-planning", "product-logic-and-intelligence-grill",
   "real-ai-integration-planning"],
  ["plans/active/<slug>/11-ai-plan.md", "plans/active/<slug>/ai/**"]),
 ("integration-mcp-architect", "planning", "Integration & MCP Architect", "balanced_reasoning",
  "Owns external integrations, MCP selection, access boundaries, tool allowlists, fallbacks.",
  ["external integrations", "MCP selection", "access boundaries", "tool allowlists",
   "fallback integration behavior", "environment separation"],
  ["integration-planning", "mcp-governance-planning"],
  ["plans/active/<slug>/12-integration-mcp-plan.md"]),
 ("infrastructure-release-architect", "planning", "Infrastructure & Release Architect", "balanced_reasoning",
  "Owns environments, infrastructure, CI/CD, deploy, migration order, release, rollback, DR.",
  ["environments", "infrastructure", "CI/CD", "deploy", "migration order", "release",
   "rollback", "disaster recovery"],
  ["infrastructure-planning", "environment-strategy"],
  ["plans/active/<slug>/13-infrastructure-environment-plan.md"]),
 ("qa-validation-architect", "planning", "QA & Validation Architect", "balanced_reasoning",
  "Owns test strategy, acceptance-test mapping, edge cases, regression, browser QA, final validation.",
  ["test strategy", "acceptance-test mapping", "edge cases", "regression",
   "browser QA", "final validation"],
  ["test-strategy-planning"],
  ["plans/active/<slug>/16-test-validation-plan.md"]),
 ("performance-observability-architect", "planning", "Performance & Observability Architect", "balanced_reasoning",
  "Owns performance budgets, observability, logs, metrics, traces, alerts, profiling, cost telemetry.",
  ["performance budgets", "observability", "logs", "metrics", "traces", "alerts",
   "profiling", "cost telemetry"],
  ["performance-budget-planning", "observability-planning"],
  ["plans/active/<slug>/14-observability-plan.md", "plans/active/<slug>/15-performance-plan.md"]),
 ("task-decomposer", "planning", "Task Decomposer", "balanced_reasoning",
  "Owns atomic tasks, dependencies, phases, parallelism, file ownership, validation commands.",
  ["atomic tasks", "dependencies", "implementation phases", "parallelism",
   "file ownership", "validation commands"],
  ["task-decomposition", "file-ownership-planning", "agent-assignment", "skill-assignment"],
  ["plans/active/<slug>/18-task-manifest.yaml"]),
 ("skill-curator", "planning", "Skill Curator", "fast_read_only",
  "Owns skill discovery, community evaluation, local fallback mapping, new-skill creation.",
  ["available skill discovery", "community skill evaluation", "local fallback mapping",
   "project-specific skill creation", "runtime classification"],
  ["skill-assignment"],
  ["plans/active/<slug>/21-skill-map.yaml"]),
 ("codex-handoff-writer", "planning", "Codex Handoff Writer", "balanced_reasoning",
  "Owns the implementation brief, order, task manifest, context packets, non-negotiables.",
  ["implementation brief", "exact implementation order", "task manifest",
   "context packets", "non-negotiable rules", "completion report format"],
  ["codex-handoff-generation", "context-packet-generation"],
  ["plans/active/<slug>/28-codex-handoff.md", "plans/active/<slug>/29-codex-start.md"]),
 ("plan-consistency-judge", "planning", "Plan Consistency Judge", "validation_independent",
  "Independent judge that finds omissions and ambiguity; must be separate from synthesis.",
  ["omissions", "contradictions", "vague requirements", "missing tests",
   "traceability breaks", "implementation ambiguity", "cross-layer gaps",
   "AI-vs-deterministic responsibility drift", "frontend completeness",
   "real-AI-integration completeness", "production-readiness", "gate-state separation",
   "fake production paths"],
  ["plan-consistency-validation", "requirement-traceability",
   "cross-layer-reconciliation"],
  ["plans/active/<slug>/30-plan-validation-report.md"]),

 # ---- implementation agents ----
 ("autonomous-execution-supervisor", "implementation", "Autonomous Execution Supervisor", "highest_reasoning",
  "Primary implementation coordinator; owns the implementation state machine.",
  ["own the implementation state machine", "dispatch tasks", "manage dependencies",
   "manage parallel work", "ensure validations run", "reopen failed tasks",
   "invoke recovery", "prevent premature completion", "produce the final result"],
  ["implement-max", "active-plan-reader", "task-manifest-runner", "plan-scope-guard"],
  ["runtime/**"]),
 ("repository-explorer", "implementation", "Repository Explorer", "fast_read_only",
  "Read-only mapper of the existing repository.",
  ["map the existing repository", "locate relevant files", "identify conventions",
   "identify integration points", "return concise evidence"],
  ["active-plan-reader"], []),
 ("implementation-task-runner", "implementation", "Implementation Task Runner", "implementation_heavy",
  "Executes bounded tasks from the manifest; must not expand scope.",
  ["execute a single manifest task", "stay within declared file ownership",
   "run validation commands", "return control on completion or failure"],
  ["task-manifest-runner", "context-packet-loader", "plan-scope-guard"], []),
 ("frontend-uiux-builder", "implementation", "Frontend & UI/UX Builder", "implementation_heavy",
  "Builds frontend, components, layout, states, accessibility, animation, perceived performance.",
  ["frontend", "components", "layout", "responsive behavior", "accessibility",
   "loading", "empty states", "error states", "animation", "visual consistency",
   "perceived performance", "product translation", "creative UI concept",
   "information hierarchy", "frontend-backend contract wiring", "AI-state surfaces"],
  ["frontend-implementation", "frontend-design-fidelity", "responsive-implementation",
   "accessibility-implementation", "frontend-product-translation",
   "creative-ui-concept", "information-hierarchy", "frontend-design-system",
   "animation-and-microinteraction", "frontend-state-completeness",
   "loading-error-empty-states", "frontend-backend-contract",
   "design-reference-compliance", "frontend-performance"],
  ["<frontend source paths from plan>"]),
 ("backend-api-builder", "implementation", "Backend & API Builder", "implementation_heavy",
  "Builds APIs, services, business logic, validation, jobs, queues, server-side tests.",
  ["APIs", "services", "business logic", "validation", "jobs", "queues",
   "server-side tests"],
  ["backend-api-implementation", "business-logic-implementation", "unit-test-loop"],
  ["<backend source paths from plan>"]),
 ("database-migration-builder", "implementation", "Database & Migration Builder", "implementation_heavy",
  "Builds schemas, migrations, seeds, indexes, constraints, repositories, database tests.",
  ["schemas", "migrations", "seeds", "indexes", "constraints", "repositories",
   "database tests", "migration verification"],
  ["database-schema-implementation", "database-migration-implementation",
   "database-test-and-drift-check"],
  ["database/**"]),
 ("auth-authorization-builder", "implementation", "Auth & Authorization Builder", "implementation_heavy",
  "Builds authentication, sessions, roles, permissions, org isolation, security tests.",
  ["authentication", "sessions", "roles", "permissions", "organization isolation",
   "security tests"],
  ["auth-implementation", "authorization-validation"],
  ["<auth source paths from plan>"]),
 ("ai-orchestration-builder", "implementation", "AI Orchestration Builder", "implementation_heavy",
  "Builds prompts, model interfaces, tools, memory, structured output, validation, fallback, evals.",
  ["prompts", "model interfaces", "tools", "memory", "structured output",
   "validation", "fallback", "AI evaluations", "real provider adapter",
   "startup config validation"],
  ["ai-orchestration-implementation", "ai-output-validation",
   "ai-interface-implementation"],
  ["<ai source paths from plan>"]),
 ("integration-builder", "implementation", "Integration Builder", "implementation_heavy",
  "Builds external API adapters, MCP-backed workflows, webhooks, retries, mocks, contract tests.",
  ["external APIs", "MCP-backed workflows", "adapters", "webhooks", "retries",
   "mocks", "contract tests"],
  ["integration-implementation", "mcp-tool-usage"],
  ["<integration source paths from plan>"]),
 ("infrastructure-builder", "implementation", "Infrastructure Builder", "implementation_heavy",
  "Builds containers, IaC, environment setup, CI/CD, deploy config, observability wiring.",
  ["containers", "infrastructure as code", "environment setup", "CI/CD",
   "deploy configuration", "observability wiring"],
  ["infrastructure-implementation", "environment-bootstrap", "observability-implementation"],
  ["infra/**", ".github/**"]),
 ("qa-test-validator", "implementation", "QA Test Validator", "balanced_reasoning",
  "Owns unit, integration, contract, E2E, regression, and acceptance-criteria tests.",
  ["unit tests", "integration tests", "contract tests", "E2E", "regression",
   "acceptance criteria"],
  ["unit-test-loop", "integration-test-loop", "acceptance-criteria-validation"],
  ["<test paths from plan>"]),
 ("browser-ui-validator", "implementation", "Browser UI Validator", "balanced_reasoning",
  "Runs the app and validates real flows, console, network, responsiveness, a11y. Read-only unless combined.",
  ["running the application", "navigating real flows", "checking browser console",
   "checking network failures", "checking responsiveness", "checking accessibility",
   "detecting unexpected placeholders", "detecting buttons without actions",
   "detecting forms without validation", "detecting impossible loading states",
   "capturing evidence", "reporting visual and behavioral mismatches"],
  ["e2e-browser-validation", "accessibility-implementation", "visual-regression"], []),
 ("frontend-experience-reviewer", "implementation", "Frontend Experience Reviewer", "validation_independent",
  "Independent frontend quality gate: judges whether the UI expresses the product, is not generic, "
  "exposes product logic, and follows the reference package. Owns frontend_experience_review_passed.",
  ["visual concept expresses the product", "interface is not generic",
   "important logic is visible", "hierarchy is meaningful", "space used intentionally",
   "no unexplained empty areas", "appropriate visualization", "feedback + transitions exist",
   "product feels complete", "follows the reference package", "primary flows understandable"],
  ["frontend-experience-review", "design-reference-compliance", "visual-regression"], []),
 ("production-verification-agent", "implementation", "Production Verification Agent", "balanced_reasoning",
  "Runs the clean production-like verification (install->migrate->build->start->health->flows->"
  "auth->persistence->AI config->evidence). Owns production_like_run_verified.",
  ["clean install", "database init + migrate", "build", "start + health",
   "core browser flows", "auth + persistence checks", "AI config behavior (present/absent creds)",
   "log/console/network inspection", "security + performance checks", "evidence capture"],
  ["production-like-run-verification", "active-plan-reader", "e2e-browser-validation"], []),
 ("performance-reviewer", "implementation", "Performance Reviewer", "balanced_reasoning",
  "Reviews profiling, latency, rendering, bundle size, slow queries, interaction smoothness.",
  ["profiling", "latency", "rendering", "bundle size", "slow queries",
   "interaction smoothness", "performance regressions"],
  ["performance-audit"], []),
 ("security-reviewer", "implementation", "Security Reviewer", "balanced_reasoning",
  "Read-only-preferred review of auth boundaries, injection, secrets, permissions, dependencies.",
  ["auth boundaries", "injection", "secrets", "permissions", "unsafe dependencies",
   "data exposure", "insecure configuration"],
  ["security-review"], []),
 ("failure-recovery-agent", "implementation", "Failure Recovery Agent", "highest_reasoning",
  "Diagnoses failure, classifies cause, changes strategy, reverts only problematic changes.",
  ["diagnosing failure", "classifying cause", "reviewing previous attempts",
   "selecting a different strategy", "reverting only problematic changes",
   "creating corrective tasks", "preventing infinite repetition"],
  ["failure-diagnosis", "failure-recovery", "checkpoint-and-rollback"], []),
 ("documentation-writer", "implementation", "Documentation Writer", "balanced_reasoning",
  "Writes setup, architecture, environment, operations, troubleshooting, final docs.",
  ["setup", "architecture", "environment", "operations", "troubleshooting",
   "final implementation documentation"],
  ["phase-completion-reporting", "final-delivery-report"],
  ["docs/**", "README.md"]),
 ("final-acceptance-judge", "implementation", "Final Acceptance Judge", "validation_independent",
  "Independent, read-only. Compares implementation to plan; prevents false completion.",
  ["comparing implementation against the plan", "checking acceptance criteria",
   "checking tests and evidence", "identifying missing work",
   "reopening failed criteria", "preventing false completion"],
  ["final-plan-comparison", "acceptance-criteria-validation"], []),
]

# ---------------------------------------------------------------------------
# SKILLS  (name, scope, purpose, procedure[], triggers[], when_not[])
# scope: planning | implementation | shared
# ---------------------------------------------------------------------------
SKILLS = [
 # ---- planning skills (section 15) ----
 ("plan-max-orchestration", "planning",
  "Drive the full closed-loop /plan_max pipeline and produce the audited Codex package.",
  ["Run repository/context preflight; normalize intent; invoke grill-me-planning three passes.",
   "Run product-logic-and-intelligence-grill: fix AI-vs-deterministic ownership before specifying.",
   "Classify gaps with decision-resolution; resolve A-D, group E questions only.",
   "Invoke domain planning agents/skills for EVERY applicable dimension.",
   "Run frontend-reference-intake, then frontend-experience-grill, then screen + interaction "
   "contracts; when AI is central run real-ai-integration-planning.",
   "Run cross-layer-reconciliation (vertical-traceability), implementation-deliverables-planning, "
   "and production-readiness-planning.",
   "Assemble the numbered plan package under plans/active/<slug>/ with implementation gates PENDING.",
   "Embed the independent audit: invoke plan-consistency-judge on the artifacts (not the report); "
   "auto-repair critical/major findings; recompute counts/refs/version/hash; re-audit; repeat.",
   "Only mark IMPLEMENTATION_READY when the independent judge clears all critical/major findings."],
  ["/plan_max invoked", "/plan_resume"],
  ["during implementation", "to write product code",
   "to stop after producing files without auditing content"]),
 ("grill-me-planning", "planning",
  "Adversarial interrogation of the product and plan; produce concrete findings, not ceremony.",
  ["Pass 1 (product reality): is the stated problem the real problem? who has it? why now?",
   "Pass 2 (system completeness): sweep every dimension (users..rollback) for gaps.",
   "Pass 3 (implementation ambiguity): could Codex implement without guessing?",
   "Record findings with severity and the requirement/area they affect.",
   "Emit high-value questions only for material product ambiguity (Category E)."],
  ["every planning request", "/grill_max"],
  ["never skip; it is mandatory for every plan"]),
 ("product-discovery", "planning",
  "Expand the idea into problem, users, value, and success definition.",
  ["Restate the problem and who experiences it.",
   "Identify how it is handled today and why a new system is needed.",
   "Define the value and the concrete definition of success.",
   "List explicit vs implicit requirements and non-negotiables."],
  ["Phase 1-2 of planning"], ["for pure technical decisions"]),
 ("requirement-extraction", "planning",
  "Turn intent into testable requirements with IDs.",
  ["Enumerate functional requirements with FR-### ids and all required fields.",
   "Enumerate non-functional requirements with NFR-### ids and measurable targets.",
   "Attach actors, preconditions, validation, errors, permissions, dependencies.",
   "Ensure each requirement is testable and unambiguous."],
  ["Phase 8 product plan"], ["for vague wishlists without acceptance criteria"]),
 ("requirement-completeness-audit", "planning",
  "Detect missing requirements across all system dimensions.",
  ["Check coverage of users, roles, tenancy, journeys, backend, frontend, data, auth, AI.",
   "Check integrations, notifications, search, admin, observability, failure, rollback.",
   "Flag every missing dimension as a gap for decision-resolution.",
   "Confirm no dimension is silently skipped."],
  ["after first draft of the product plan"], []),
 ("assumption-management", "planning",
  "Record and track every autonomously-resolved assumption.",
  ["For each Category B-D resolution create an ASM-### entry.",
   "Record confidence, reason, source, reversibility, consequence-if-wrong.",
   "Link assumptions to affected requirements.",
   "Validate the ledger against assumption-ledger.schema.json."],
  ["Phase 7"], []),
 ("decision-resolution", "planning",
  "Classify every gap into Categories A-F and resolve or escalate correctly.",
  ["Classify each missing decision A/B/C/D/E/F.",
   "Resolve A-D autonomously; record C/D in the decision ledger.",
   "Group all E questions into one round with recommended defaults.",
   "Treat F as an external dependency, not a planning ambiguity."],
  ["Phase 5-6"], ["to ask questions Claude can answer itself"]),
 ("user-flow-planning", "planning",
  "Design core user journeys with success, alternative, and error paths.",
  ["For each journey assign FLOW-### and actor + trigger + preconditions.",
   "Write numbered steps and system responses.",
   "Define success, alternative, error, cancellation, and recovery paths.",
   "List data changed, audit events, and acceptance criteria."],
  ["Phase 8.5"], []),
 ("business-rule-specification", "planning",
  "Specify exact business rules with conditions, precedence, and examples.",
  ["Assign RULE-### and state trigger, inputs, exact condition, output.",
   "Define precedence, exceptions, failure behavior, audit requirement.",
   "Provide worked examples and tests."],
  ["Phase 8.8"], []),
 ("technical-architecture-planning", "planning",
  "Produce the technical architecture with diagrams and ADRs.",
  ["Define components, boundaries, dependency rules, and flows.",
   "Diagram key request/event flows in Mermaid.",
   "Record technology choices, alternatives, trade-offs, and ADR-### entries."],
  ["Phase 9"], ["to specify product requirements"]),
 ("data-architecture-planning", "planning",
  "Design the data model and produce a machine-readable representation.",
  ["Decide persistence need and database kind(s).",
   "Define entities (DB-###), fields, types, relationships, constraints, indexes.",
   "Mark ownership, classification, personal data, retention.",
   "Emit data-model.yaml validating against data-model.schema.json."],
  ["Phase 10"], []),
 ("database-selection", "planning",
  "Select the database from requirements, not by default.",
  ["Map requirements to relational/document/kv/graph/vector/search/cache needs.",
   "Recommend a database + provider with rationale and alternatives.",
   "Define local/test/staging/production database strategy."],
  ["Phase 10"], ["to force one database on every project"]),
 ("migration-planning", "planning",
  "Plan migration ordering, rollback, and drift checks.",
  ["Choose a migration tool/approach.",
   "Define backward-compatible + expand-and-contract strategy for destructive changes.",
   "Define per-migration rollback and a schema-drift check."],
  ["Phase 10"], []),
 ("auth-authorization-planning", "planning",
  "Design identity, sessions, and the authorization model.",
  ["Decide auth methods and account lifecycle.",
   "Define session/token strategy, recovery, verification.",
   "Enumerate roles (AUTH-###), permissions, boundaries, privileged actions, audit."],
  ["Phase 14"], []),
 ("security-threat-model-planning", "planning",
  "Build a threat model with misuse cases and concrete controls.",
  ["Enumerate threats and misuse cases.",
   "Attach a control (SEC-###) to each threat.",
   "Define security tests and incident telemetry mapped to acceptance criteria."],
  ["Phase 14"], []),
 ("backend-api-planning", "planning",
  "Design domain services and API contracts.",
  ["Define domain modules, service boundaries, and the error model.",
   "Specify every endpoint (API-###) with request/response schemas and codes.",
   "Define idempotency, side effects, events, jobs, queues, observability, tests."],
  ["Phase 11 & 13"], []),
 ("frontend-uiux-planning", "planning",
  "Design screens and interactions with all states.",
  ["For each screen assign UI-### and define layout, components, primary action.",
   "Define default/loading/empty/error/success/disabled/partial-data states.",
   "Define responsive, keyboard, accessibility, motion, and visual acceptance criteria.",
   "Consider community front-design skills; fall back to this skill if absent."],
  ["Phase 12"], []),
 ("responsive-design-planning", "planning",
  "Define responsive breakpoints and layout behavior.",
  ["Define breakpoints and per-breakpoint layout for each screen.",
   "Define touch/keyboard behavior and reflow rules.",
   "Define acceptance criteria for small/medium/large viewports."],
  ["Phase 12"], []),
 ("accessibility-planning", "planning",
  "Plan accessibility to a stated conformance target.",
  ["Choose a conformance target (e.g. WCAG 2.2 AA).",
   "Define focus order, labels, roles, contrast, and keyboard operability per screen.",
   "Define accessibility acceptance criteria and test approach."],
  ["Phase 12"], []),
 ("motion-performance-planning", "planning",
  "Plan motion and perceived performance.",
  ["Define motion principles, durations, and reduced-motion behavior.",
   "Define perceived-performance techniques (skeletons, optimistic UI).",
   "Attach animation acceptance criteria."],
  ["Phase 12"], []),
 ("ai-flow-planning", "planning",
  "Specify AI behavior with exact inputs, outputs, and validation.",
  ["Assign AI-### and state purpose and where deterministic logic is required.",
   "Define inputs, context, tools, memory, and the output schema.",
   "Define grounding/citations, hallucination, refusal, and fallback behavior.",
   "Define token/latency/cost budgets and a model-independent interface."],
  ["Phase 15"], ["to write 'use AI to analyze the data' without a contract"]),
 ("ai-evaluation-planning", "planning",
  "Plan AI evaluation with golden and red-team cases.",
  ["Define golden test cases and expected outputs.",
   "Define red-team / prompt-injection cases.",
   "Define quality metrics and pass thresholds mapped to acceptance criteria."],
  ["Phase 15"], []),
 ("integration-planning", "planning",
  "Specify external integrations with fallback and mock strategy.",
  ["Assign INT-### and define auth, data in/out, triggers, timeouts, retries.",
   "Define failure behavior, fallback, sandbox, and mock strategy.",
   "Define contract tests."],
  ["Phase 13"], []),
 ("mcp-governance-planning", "planning",
  "Select and govern MCPs with least privilege.",
  ["Select only necessary MCPs from the registry.",
   "Apply least privilege, read/write separation, and environment separation.",
   "Define tool allowlists, blocked destructive tools, health checks, fallbacks.",
   "Generate separate Claude and Codex MCP configuration."],
  ["Phase 20"], ["to enable every MCP globally"]),
 ("infrastructure-planning", "planning",
  "Plan containers, IaC, hosting, CI/CD, backups, and disaster recovery.",
  ["Define container + IaC strategy and hosting.",
   "Define workers, queues, schedules, storage, and backups.",
   "Define CI/CD, release, rollback, and disaster recovery."],
  ["Phase 16"], []),
 ("environment-strategy", "planning",
  "Define local, test, development, staging, and production environments.",
  ["For each environment define services, database, variables (names only).",
   "Define network boundaries, access model, deployment, and migrations.",
   "Define monitoring, test data, teardown, and rollback."],
  ["Phase 16"], ["to place secret values anywhere"]),
 ("observability-planning", "planning",
  "Plan logs, metrics, traces, dashboards, and alerts with redaction.",
  ["Define structured log fields and correlation IDs.",
   "Define metrics, traces, dashboards, and alerts.",
   "Define AI cost/latency, MCP operations, audit events, retention, redaction."],
  ["Phase 17"], []),
 ("performance-budget-planning", "planning",
  "Set measurable performance budgets and a regression strategy.",
  ["Set numeric budgets for load, latency, jobs, AI, bundle, memory.",
   "Define profiling, load testing, and regression detection.",
   "Define cost/context budgets via capability classes."],
  ["Phase 18 & 21"], []),
 ("test-strategy-planning", "planning",
  "Plan the full test pyramid and map every acceptance criterion to a test.",
  ["Define static analysis, unit, integration, contract, DB, auth, AI, E2E, a11y tests.",
   "Map each AC-### to >=1 TEST-###.",
   "Identify where manual QA is required."],
  ["Phase 19"], []),
 ("task-decomposition", "planning",
  "Break the system into atomic, verifiable tasks.",
  ["Create TASK-### entries with objective, requirements, dependencies, files.",
   "Assign agent, skills, validation commands, and acceptance criteria.",
   "Ensure the dependency graph is a DAG and tasks are small.",
   "Validate against task-manifest.schema.json."],
  ["Phase 22"], ["to write 'build the backend' as one task"]),
 ("agent-assignment", "planning",
  "Assign each task to a Codex agent and produce the agent map.",
  ["Map each task to exactly one assigned agent.",
   "Define per-agent tools, model profile, and file ownership.",
   "Validate against agent-map.schema.json."],
  ["Phase 23"], []),
 ("skill-assignment", "planning",
  "Classify and assign skills; ensure local fallbacks.",
  ["Classify each skill core/project/community/local-fallback/new.",
   "Ensure every community skill has a local fallback.",
   "Validate against skill-map.schema.json."],
  ["Phase 24"], []),
 ("file-ownership-planning", "planning",
  "Assign file ownership and parallelization groups to prevent write conflicts.",
  ["Assign each owned path a mode and owner.",
   "Serialize shared schema/config/manifests/routing/types/migrations.",
   "Parallelize independent modules and read-only reviews.",
   "Validate against file-ownership.schema.json."],
  ["Phase 25"], []),
 ("context-packet-generation", "planning",
  "Produce a focused context packet per task.",
  ["Include only the task's requirements, architecture, files, tests, skills, MCP tools.",
   "State the output contract and stop conditions.",
   "Never include the entire planning corpus."],
  ["Phase 27"], []),
 ("codex-handoff-generation", "planning",
  "Produce a self-contained Codex handoff and start file.",
  ["Write the implementation brief and exact order.",
   "Reference the task manifest and context packets.",
   "State non-negotiable rules and the completion report format.",
   "Ensure no material decision lives only in chat history."],
  ["Phase 27"], []),
 ("plan-consistency-validation", "planning",
  "Independently validate plan completeness and traceability before handoff.",
  ["Run every check in template 32 and compute a validation score.",
   "List critical findings; do not mark ready with open criticals.",
   "Assess content quality, not just file existence."],
  ["Phase 28", "/plan_validate"],
  ["to rubber-stamp a plan because files exist"]),
 ("requirement-traceability", "planning",
  "Build and check the full traceability graph.",
  ["Build goal->requirement->task->files and requirement->AC->test->evidence maps.",
   "Detect orphan requirements, tasks, and acceptance criteria.",
   "Validate against traceability.schema.json."],
  ["Phase 28"], []),

 # ---- production-complete planning skills ----
 ("frontend-reference-intake", "planning",
  "Inspect and incorporate the project's frontend reference package before frontend planning.",
  ["Read project-reference/frontend/ (FRONTEND_REFERENCE.md, design-tokens.yaml, "
   "screen-inventory.yaml, assets/, inspiration/).",
   "Classify each reference MUST_FOLLOW/STRONG_INSPIRATION/GENERAL_INSPIRATION/AVOID.",
   "If absent/empty, infer a direction from the product and propose a reference file.",
   "Ask only grouped material visual questions when identity changes substantially.",
   "Record provenance (user/references/inference) for each decision."],
  ["Phase 12 (before frontend planning)"],
  ["to overwrite user references", "to ask reversible visual choices"]),
 ("product-logic-and-intelligence-grill", "planning",
  "Determine the central value and who owns each decision (AI vs deterministic vs frontend vs human).",
  ["Identify the actual central value and whether AI, rules, workflow, or a combination produces it.",
   "For each step decide owner, decision_type, inputs, context, tools, output contract, fallback.",
   "List decisions that must never be delegated to AI and the behavior when AI is unavailable.",
   "Reject plans that replace intended AI-centered behavior with a fixed automated flow.",
   "Emit the intelligence responsibility matrix (ai-responsibility-matrix.schema.json)."],
  ["mandatory after intent + system grill", "AI-first or AI-assisted products"],
  ["to let a fixed workflow masquerade as AI", "to write 'use AI' without owner + contract"]),
 ("frontend-experience-grill", "planning",
  "Adversarial frontend review: product communication, IA, creativity, usability, responsiveness, visual quality.",
  ["Challenge whether the UI communicates central value and what the AI is doing.",
   "Challenge information architecture, progressive disclosure, and what deserves visualization.",
   "Challenge generic-dashboard risk and identify concrete custom visualization.",
   "Challenge usability, responsiveness, and visual quality (hierarchy/spacing/dead areas).",
   "Emit concrete frontend decisions and a visual-quality-review verdict per dimension."],
  ["mandatory for every product with a UI", "/plan_frontend_max"],
  ["to output generic design advice instead of decisions"]),
 ("frontend-screen-contract-planning", "planning",
  "Produce detailed per-surface screen contracts with every state and data/backend/AI dependency.",
  ["For each page/route/modal/panel/component emit a UI-### screen contract.",
   "Define all applicable states (default/loading/streaming/generating/reconnecting/empty/"
   "partial_data/error/success/disabled/permission_denied).",
   "Bind each surface to its requirement, API/action, state-machine state, and tests.",
   "Add component and frontend-state inventories.",
   "Validate against screen-contract/component-contract/frontend-state schemas."],
  ["Phase 12 (deep frontend plan)"],
  ["to emit a list of page names", "to allow fake/static data in a production path"]),
 ("frontend-backend-contract-planning", "planning",
  "Bind every frontend interaction to its backend/local behavior end to end.",
  ["For each user action emit an IX-### interaction contract.",
   "Define request contract, backend handler, business rule, AI behavior, database effect.",
   "Define success + error responses, loading/streaming/retry/optimistic behavior, feedback.",
   "Reject buttons with no contract and user-visible backend features with no surface.",
   "Validate against interaction-contract.schema.json."],
  ["Phase 12-13 reconciliation"],
  ["to leave a button without an implementation contract"]),
 ("real-ai-integration-planning", "planning",
  "Specify a production-capable AI provider integration and the centrality tests that prove it.",
  ["Define the provider-independent interface AND a concrete provider adapter.",
   "Specify env-var names, timeout, retry, rate-limit, structured output, prompt versioning.",
   "Enumerate the production path frontend->endpoint->validation->context->interface->adapter->"
   "provider->output validation->persistence->response/stream.",
   "Define centrality tests and forbid scripted production conversations.",
   "Define startup validation and mock-mode policy (never the production default).",
   "Validate against ai-provider-contract + real-ai-integration-plan schemas."],
  ["Phase 15 when AI is central"],
  ["to plan a scripted/fake production AI path", "to place secret values anywhere"]),
 ("cross-layer-reconciliation", "planning",
  "Reconcile product behavior across every applicable layer into vertical traceability.",
  ["For each user-facing requirement map goal->rule->AI/deterministic->backend->data/integration->"
   "API->frontend surface->frontend state->acceptance->test->evidence.",
   "Detect any missing applicable layer and reopen it.",
   "Confirm AI requirements have AI behaviors and UI requirements have surfaces + states.",
   "Emit vertical-traceability.yaml validating against vertical-traceability.schema.json."],
  ["Phase after all domain plans", "/plan_reconcile", "after any material plan revision"],
  ["to skip a layer that applies to the product"]),
 ("implementation-deliverables-planning", "planning",
  "State exactly what Codex must deliver and how each deliverable is proven complete.",
  ["Enumerate deliverables (frontend/backend/database/auth/ai_integration/environments/e2e/"
   "observability/docs/deployment/final_report) with DEL-### ids.",
   "State expected files, runtime behavior, dependencies, configuration, tests, evidence.",
   "State objective completion conditions and map each to completion gates.",
   "Validate against implementation-deliverable.schema.json."],
  ["Phase 27 (handoff)"],
  ["to describe product behavior instead of deliverables"]),
 ("production-readiness-planning", "planning",
  "Prove every applicable vertical layer is planned, gated, and not superficial or deferred.",
  ["Enumerate all layers and mark applicability + planned + implementation gate.",
   "Require frontend when UI exists, DB when persistence, auth when private/roles, real AI path "
   "when AI is central.",
   "Define the production-like run steps Codex must execute.",
   "Fail readiness when an applicable layer is omitted, superficial, or delegated to Codex.",
   "Validate against production-readiness + production-like-run schemas."],
  ["Phase 27-28"],
  ["to mark IMPLEMENTATION_READY with an applicable layer missing"]),

 # ---- implementation skills (section 19) ----
 ("implement-max", "implementation",
  "Entry skill: implement the active plan until all completion gates pass.",
  ["Locate and validate the active plan; read PLAN_METADATA and EXECUTION.lock.",
   "Load the task manifest and execute tasks in dependency order.",
   "Run validations after each task and phase; repair failures autonomously.",
   "Preserve product scope; record deviations; continue until gates pass.",
   "Invoke the final-acceptance-judge before declaring completion."],
  ["'Implement the active system plan using the implement-max skill.'"],
  ["to reinterpret the product's core objective"]),
 ("active-plan-reader", "implementation",
  "Locate, load, and validate the active plan package and its version/hash.",
  ["Find plans/active/<slug>/ and read PLAN_METADATA.yaml.",
   "Verify the plan hash and EXECUTION.lock status.",
   "Load task manifest, agent map, skill map, and acceptance criteria.",
   "Fail fast if the package is incomplete or conflicting."],
  ["start of implementation"], ["to edit the plan"]),
 ("plan-scope-guard", "implementation",
  "Prevent scope creep and unauthorized product-behavior changes.",
  ["Compare proposed changes to the active requirements.",
   "Block Level-3 (product behavior) changes; require a new plan version.",
   "Allow Level 0-2 deviations with logging/ADR per the deviation policy."],
  ["before any code change"], []),
 ("task-manifest-runner", "implementation",
  "Execute manifest tasks in dependency order with validations.",
  ["Select the next unblocked task from the DAG.",
   "Load its context packet and enforce file ownership.",
   "Run the task's validation commands; on failure escalate to failure-diagnosis.",
   "Mark status and update the execution ledger."],
  ["main implementation loop"], []),
 ("context-packet-loader", "implementation",
  "Load only the focused context a task needs.",
  ["Read the task's context packet.",
   "Load referenced requirements, files, tests, and skills only.",
   "Reject work that requires context outside the packet without escalation."],
  ["before executing a task"], ["to load the entire planning corpus"]),
 ("repository-bootstrap", "implementation",
  "Bootstrap the project skeleton and detect toolchain commands.",
  ["Detect package manager, lint, test, build, and migration commands.",
   "Record detected commands in the active plan.",
   "Create the minimal runnable skeleton per the architecture."],
  ["BOOTSTRAPPING state"], []),
 ("dependency-management", "implementation",
  "Install and pin normal project dependencies safely.",
  ["Install required dependencies with the detected package manager.",
   "Pin versions and record them.",
   "Never install from untrusted sources; run a dependency security check."],
  ["bootstrap and as needed"], []),
 ("frontend-implementation", "implementation",
  "Implement frontend routes, components, and all screen states.",
  ["Implement routes/layouts/components per the frontend plan.",
   "Implement default/loading/empty/error/success/disabled states.",
   "Wire client validation and server-state; add component tests."],
  ["frontend tasks"], ["backend or schema files"]),
 ("frontend-design-fidelity", "implementation",
  "Match the implementation to the design direction and tokens.",
  ["Apply design tokens (type, spacing, grid, color).",
   "Verify hierarchy, alignment, and motion against the plan.",
   "Capture before/after evidence for visual acceptance criteria."],
  ["frontend tasks with a visual bar"], []),
 ("responsive-implementation", "implementation",
  "Implement responsive behavior across breakpoints.",
  ["Implement per-breakpoint layouts.",
   "Verify reflow, touch, and keyboard behavior.",
   "Add responsive checks to browser validation."],
  ["frontend tasks"], []),
 ("accessibility-implementation", "implementation",
  "Implement accessibility to the target conformance level.",
  ["Add semantic roles, labels, and focus management.",
   "Verify contrast and keyboard operability.",
   "Run an automated a11y check and record results."],
  ["frontend tasks", "browser validation"], []),
 ("backend-api-implementation", "implementation",
  "Implement API endpoints exactly to contract.",
  ["Implement each endpoint per its API-### contract.",
   "Enforce request/response schemas, validation, and error codes.",
   "Emit events and side effects as specified; add tests."],
  ["backend tasks"], ["frontend component files"]),
 ("business-logic-implementation", "implementation",
  "Implement business rules deterministically.",
  ["Implement each RULE-### with its exact condition and precedence.",
   "Handle exceptions and failure behavior.",
   "Add unit tests including the rule's worked examples."],
  ["backend tasks"], []),
 ("database-schema-implementation", "implementation",
  "Implement the schema declaratively from the data model.",
  ["Create schema objects for each DB-### entity.",
   "Add constraints, unique rules, and indexes mapped to queries.",
   "Keep database/schema/ as the source of truth."],
  ["database tasks"], ["application source outside database/"]),
 ("database-migration-implementation", "implementation",
  "Implement ordered, reversible migrations.",
  ["Write forward + rollback migrations for each change.",
   "Apply to the local/test database and verify.",
   "Use expand-and-contract for destructive changes."],
  ["database tasks"], []),
 ("database-test-and-drift-check", "implementation",
  "Test the database and check for schema drift.",
  ["Run database tests including row-level policies where used.",
   "Diff the applied schema against the declared schema.",
   "Fail the gate on drift or failing tests."],
  ["after migrations"], []),
 ("auth-implementation", "implementation",
  "Implement authentication and session management.",
  ["Implement account lifecycle, login/logout, and sessions.",
   "Reference secrets by env-var name only.",
   "Add auth tests covering success and failure paths."],
  ["auth tasks"], []),
 ("authorization-validation", "implementation",
  "Implement and test authorization boundaries and isolation.",
  ["Enforce roles/permissions on every protected action.",
   "Enforce organization/tenant isolation.",
   "Add authorization tests including negative cases."],
  ["auth tasks"], []),
 ("ai-orchestration-implementation", "implementation",
  "Implement AI flows behind model-independent interfaces.",
  ["Implement prompt/tool/memory contracts and structured output.",
   "Add validation and fallback per the AI plan.",
   "Keep the model behind an interface for substitution."],
  ["AI tasks"], []),
 ("ai-output-validation", "implementation",
  "Validate AI outputs against schema and evals.",
  ["Validate every AI output against its output schema.",
   "Run golden and red-team evals; enforce thresholds.",
   "Trigger fallback/refusal behavior on low confidence."],
  ["AI tasks"], []),
 ("integration-implementation", "implementation",
  "Implement external integrations with retries, mocks, and contract tests.",
  ["Implement the adapter per the INT-### contract.",
   "Add timeouts, retries, idempotency, and fallback.",
   "Provide a mock/sandbox and contract tests."],
  ["integration tasks"], []),
 ("mcp-tool-usage", "implementation",
  "Use MCP tools within governed least-privilege boundaries.",
  ["Use only allowlisted tools for the current environment.",
   "Never use disabled/destructive tools.",
   "Fall back to the local equivalent when the MCP is unavailable."],
  ["tasks using MCP-backed workflows"], ["production writes without guards"]),
 ("infrastructure-implementation", "implementation",
  "Implement containers, IaC, and CI/CD.",
  ["Write container + IaC definitions per the infra plan.",
   "Wire CI/CD stages and deploy configuration.",
   "Never embed secret values; use env-var references."],
  ["infrastructure tasks"], []),
 ("environment-bootstrap", "implementation",
  "Bring up local/test/development environments.",
  ["Create env config from .env.example (names only).",
   "Start required services and the local database.",
   "Verify health checks pass."],
  ["environment tasks"], []),
 ("observability-implementation", "implementation",
  "Wire structured logs, metrics, traces, and alerts.",
  ["Emit structured logs with correlation IDs and redaction.",
   "Expose metrics and traces per the observability plan.",
   "Wire alerts and verify they fire in test."],
  ["observability tasks"], []),
 ("unit-test-loop", "implementation",
  "Write and run unit tests until green.",
  ["Write unit tests for the task's units.",
   "Run them; on failure escalate to failure-diagnosis.",
   "Do not mark done until unit tests pass."],
  ["every code task"], []),
 ("integration-test-loop", "implementation",
  "Write and run integration/contract tests until green.",
  ["Write integration/contract tests across module boundaries.",
   "Run them; repair failures.",
   "Verify contracts match the API/data schemas."],
  ["integration tasks"], []),
 ("e2e-browser-validation", "implementation",
  "Run real end-to-end flows in a browser and capture evidence.",
  ["Launch the app and navigate each critical flow.",
   "Check console errors, network failures, responsiveness, a11y.",
   "Capture screenshots/logs as evidence for acceptance criteria."],
  ["UI present"], ["editing code unless configured as combined role"]),
 ("acceptance-criteria-validation", "implementation",
  "Verify each acceptance criterion with evidence.",
  ["For each AC-### run its setup/action and check the expected result.",
   "Attach evidence and mark automated/manual.",
   "Reopen the mapped task on failure."],
  ["VALIDATING_ACCEPTANCE state"], []),
 ("performance-audit", "implementation",
  "Measure against performance budgets and detect regressions.",
  ["Measure load/latency/bundle/query metrics.",
   "Compare to budgets; flag regressions.",
   "Record results as the performance gate evidence."],
  ["REVIEWING state"], []),
 ("security-review", "implementation",
  "Review for injection, secrets, permissions, and unsafe config (read-only preferred).",
  ["Scan for secret exposure and insecure configuration.",
   "Check auth boundaries, injection, and permissions.",
   "Run a dependency security check; record findings."],
  ["REVIEWING state"], ["to weaken protections for convenience"]),
 ("failure-diagnosis", "implementation",
  "Classify a failure and collect minimal evidence.",
  ["Classify the failure into a category.",
   "Collect the minimal reproducing evidence.",
   "Review previous attempts before proposing a fix."],
  ["any failure"], []),
 ("failure-recovery", "implementation",
  "Apply a bounded, strategy-changing repair without infinite loops.",
  ["Choose a repair strategy different from prior identical attempts.",
   "Checkpoint, apply a bounded correction, run targeted + regression validation.",
   "After the attempt budget, escalate or mark externally blocked with a reason."],
  ["REPAIRING state"], ["identical retries"]),
 ("checkpoint-and-rollback", "implementation",
  "Create checkpoints and revert only problematic changes.",
  ["Checkpoint before risky changes.",
   "On failure revert only the failed approach, preserving good work.",
   "Record the checkpoint and rollback in the ledger."],
  ["before risky changes", "on repeated failure"], []),
 ("implementation-deviation-reporting", "implementation",
  "Record deviations per the deviation policy.",
  ["Classify the deviation level 0-3.",
   "For level 2 record an ADR and update artifacts/tests.",
   "For level 3 preserve the requirement and surface the contradiction."],
  ["on any implementation deviation"], []),
 ("phase-completion-reporting", "implementation",
  "Report phase completion and update state.",
  ["Summarize what completed and validation status.",
   "Write a phase log and update runtime state.",
   "Confirm gates relevant to the phase are green."],
  ["end of each phase"], []),
 ("final-plan-comparison", "implementation",
  "Compare the implementation to the plan before delivery.",
  ["Walk requirement->task->files and acceptance->test->evidence.",
   "List any missing or failing items and reopen them.",
   "Only pass when every required item is satisfied with evidence."],
  ["final acceptance"], ["to pass with unverified items"]),
 ("final-delivery-report", "implementation",
  "Produce the truthful, evidence-based final report.",
  ["Report every completion gate PASS/FAIL/NA with evidence.",
   "List deviations, external blockers, and honest failures.",
   "Validate against final-report.schema.json."],
  ["READY_FOR_DELIVERY"], ["to claim untested success"]),

 # ---- production-complete implementation skills (frontend depth + AI + prod) ----
 ("frontend-product-translation", "implementation",
  "Translate product requirements and the intelligence matrix into concrete frontend behavior.",
  ["Map each user-facing requirement to the surfaces and states that express it.",
   "Ensure the product's central logic is visible in the UI, not hidden.",
   "Reject generic renderings of product-specific logic."],
  ["frontend tasks"], ["to render product logic as generic cards/tables"]),
 ("frontend-design-system", "implementation",
  "Implement the design system and tokens (color, type, spacing, motion) from the plan.",
  ["Implement design tokens and primitives from frontend/design-tokens.yaml.",
   "Build reusable components with consistent spacing, type scale, and states.",
   "Keep tokens the single source of visual truth."],
  ["frontend tasks"], []),
 ("creative-ui-concept", "implementation",
  "Realize the product's differentiating visual/interaction concept, not a generic dashboard.",
  ["Implement the custom visualization/interaction identified in the frontend grill.",
   "Use timelines/process maps/comparisons/scores/simulations where the plan calls for them.",
   "Avoid dead space and cards stretched only to fill containers."],
  ["frontend tasks with a visual bar"], ["to ship a generic admin dashboard"]),
 ("information-hierarchy", "implementation",
  "Implement meaningful information hierarchy and progressive disclosure.",
  ["Make primary information primary and supporting information secondary.",
   "Apply progressive disclosure; hide advanced controls appropriately.",
   "Verify hierarchy against the frontend plan."],
  ["frontend tasks"], []),
 ("animation-and-microinteraction", "implementation",
  "Implement motion, transitions, and microinteractions with reduced-motion support.",
  ["Implement transitions and feedback per the motion plan.",
   "Respect prefers-reduced-motion.",
   "Keep durations/easings consistent with design tokens."],
  ["frontend tasks"], []),
 ("frontend-state-completeness", "implementation",
  "Implement every declared UI state, including AI states, with no impossible states.",
  ["Implement default/loading/streaming/generating/reconnecting/empty/partial/error/success/"
   "disabled/permission_denied states per contract.",
   "Wire AI states: constructing context, generating, validating, streaming, saving, retrying, "
   "provider unavailable.",
   "Add tests asserting each state renders from its trigger."],
  ["frontend tasks", "AI UI tasks"], ["to omit loading/error/empty states"]),
 ("loading-error-empty-states", "implementation",
  "Guarantee loading, error, and empty states exist and are actionable for every data surface.",
  ["Add loading, empty, and actionable error states to every data-backed surface.",
   "Ensure errors explain and offer a next action.",
   "Test each state in isolation."],
  ["frontend tasks"], []),
 ("frontend-backend-contract", "implementation",
  "Wire each interaction contract to a real backend/server action (no dead buttons, no fake data).",
  ["Implement each IX-### interaction: validation, request, handler call, response handling.",
   "Remove static/sample data from production paths; call the real API or server action.",
   "Add integration tests asserting the request/response contract holds."],
  ["frontend tasks", "integration tasks"],
  ["to leave a button without an action", "to use static fake data in production paths"]),
 ("ai-interface-implementation", "implementation",
  "Implement the production AI path behind a provider-independent interface with a real adapter.",
  ["Implement the provider-independent interface and a concrete provider adapter.",
   "Wire timeout, retry, rate-limit handling, structured output, and prompt versioning.",
   "Add startup validation for missing configuration and reference secrets by env-var name only.",
   "Add fakes/mocks for tests and an optional real-key integration test; mock is never the "
   "production default."],
  ["AI tasks when the product depends on an external provider"],
  ["to ship a scripted/fake production AI path", "to expose secrets"]),
 ("design-reference-compliance", "implementation",
  "Verify the implemented UI follows the frontend reference package.",
  ["Compare implementation to MUST_FOLLOW references and non-negotiable visual rules.",
   "Flag AVOID patterns that slipped in.",
   "Record compliance evidence for the frontend experience review."],
  ["frontend review", "REVIEWING state"], []),
 ("visual-regression", "implementation",
  "Capture and compare visual evidence for major screens; flag regressions.",
  ["Capture screenshots for major screens across breakpoints.",
   "Compare against baselines or perform structured visual review when baselines are absent.",
   "Attach evidence to visual acceptance criteria."],
  ["frontend review", "browser validation"], []),
 ("frontend-performance", "implementation",
  "Measure and enforce frontend performance budgets (load, bundle, interaction).",
  ["Measure initial load, route transitions, bundle size, and input responsiveness.",
   "Compare to the plan's budgets and flag regressions.",
   "Record results as frontend performance evidence."],
  ["frontend REVIEWING state"], []),
 ("frontend-experience-review", "implementation",
  "Independent frontend quality gate: is the UI product-expressive, complete, and reference-compliant?",
  ["Run the visual-quality-review checks across all dimensions.",
   "Reject generic UIs, hidden product logic, dead space, and stretched-to-fill layouts.",
   "Only pass frontend_experience_review_passed when the experience is complete and expressive.",
   "Emit a visual-quality-review artifact with evidence."],
  ["frontend experience review", "before frontend_experience_review_passed"],
  ["to pass because the page merely loaded"]),
 ("production-like-run-verification", "implementation",
  "Run the clean production-like verification and produce evidence for production_like_run_verified.",
  ["Install from clean, init + migrate the database, configure non-secret env, build, and start.",
   "Verify health, core browser flows, auth, persistence, and AI config behavior.",
   "Verify real-provider init when credentials exist and controlled behavior when absent.",
   "Inspect logs, browser console, and failed requests; run security + performance checks.",
   "Only pass production_like_run_verified with captured evidence."],
  ["PRODUCTION_VERIFICATION state"],
  ["to pass without a clean run + evidence"]),

 # ---- shared skills (one canonical -> two runtime adapters) ----
 ("secret-scanning", "shared",
  "Scan for secret exposure in files, diffs, and command output.",
  ["Match protected-path patterns and known secret signatures.",
   "Block reads/writes/commits that would expose secrets.",
   "Report only metadata (never the secret value)."],
  ["before any file read/write/commit", "CI"], []),
 ("schema-validation", "shared",
  "Validate a JSON/YAML artifact against a canonical schema.",
  ["Select the schema by artifact type.",
   "Validate with jsonschema_lite and report errors.",
   "Fail the gate on any schema error."],
  ["whenever an artifact is produced"], []),
 ("plan-hash-validation", "shared",
  "Verify the active plan version and content hash match EXECUTION.lock.",
  ["Compute the plan package hash.",
   "Compare against PLAN_METADATA and EXECUTION.lock.",
   "Block implementation on mismatch or conflicting versions."],
  ["start of implementation", "on plan change"], []),
]


def slug_scope(scope: str) -> str:
    return scope


def build_agent(a) -> dict:
    (aid, scope, name, model, purpose, resp, req_skills, own) = a
    is_impl = scope == "implementation"
    return {
        "id": aid,
        "canonical_name": name,
        "kind": "agent",
        "runtime_scope": ["codex"] if is_impl else ["claude"],
        "purpose": purpose,
        "behavioral_contract": "; ".join(resp),
        "responsibilities": resp,
        "model_profile": model,
        "when_to_use": f"When the plan requires {purpose[0].lower() + purpose[1:]}",
        "when_not_to_use": ("During planning" if is_impl else "During implementation")
                           + " or outside this agent's responsibilities.",
        "inputs": (["assigned task", "context packet", "active plan artifacts"]
                   if is_impl else ["user intent", "prior planning artifacts", "grill findings"]),
        "outputs": (["code/tests/docs within owned files", "validation results", "status update"]
                    if is_impl else ["planning artifact(s)", "traceable IDs", "handoff-ready content"]),
        "allowed_tools": (["read", "write", "run_tests", "run_validations", "assigned_mcp_tools"]
                          if is_impl else ["read", "write_planning_artifacts", "search", "read_only_mcp"]),
        "disallowed_actions": (["reinterpret product objective", "expose secrets",
                                "edit files outside ownership", "declare completion without gates"]
                              if is_impl else ["write product code", "expose secrets",
                                "ask questions Claude can resolve", "skip the grill process"]),
        "quality_bar": ("all owned tasks validated with evidence; no scope creep"
                        if is_impl else "every output has traceable IDs and no material TBD"),
        "stop_conditions": (["task validated or escalated to recovery", "gate failure reopens task"]
                            if is_impl else ["artifact complete and traceable", "returns to orchestrator"]),
        "required_skills": req_skills,
        "file_ownership": own,
        "claude_adapter": {
            "mechanism": "subagent" if not is_impl else "n/a",
            "path": f".claude/agents/{aid}.md" if not is_impl else None,
        },
        "codex_adapter": {
            "mechanism": "codex agent" if is_impl else "n/a",
            "path": f".codex/agents/{aid}.md" if is_impl else None,
        },
        "compatibility_notes": (
            "Planning agent; Claude-only. No Codex adapter." if not is_impl
            else "Implementation agent; Codex-only. No Claude adapter."),
        "version": VERSION,
    }


def build_skill(s) -> dict:
    (name, scope, purpose, procedure, triggers, when_not) = s
    scopes = {"planning": ["claude"], "implementation": ["codex"], "shared": ["claude", "codex"]}[scope]
    is_planning = scope == "planning"
    disallowed = (["write product code", "expose secrets", "start implementation"]
                  if is_planning else ["expose secrets", "reinterpret product scope"])
    return {
        "name": name,
        "canonical_name": name,
        "kind": "skill",
        "scope": scope,
        "runtime_scope": scopes,
        "purpose": purpose,
        "behavioral_contract": purpose,
        "invocation_triggers": triggers,
        "when_not_to_use": when_not or (["during implementation"] if is_planning else ["during product discovery"]),
        "expected_inputs": ["relevant plan artifacts", "task/context as applicable"],
        "required_context": "focused context packet or planning artifact set",
        "outputs": ["artifact(s) and/or validation results with traceable IDs"],
        "procedure": procedure,
        "checklist": [f"Completed: {step.split('.')[0].split(';')[0]}" for step in procedure],
        "quality_bar": "output is specific, testable, and traceable; no vague language",
        "failure_conditions": ["missing required fields", "vague/untestable output",
                               "secret exposure", "scope violation"],
        "allowed_tools": (["read", "write_planning_artifacts", "search"] if is_planning
                          else ["read", "write", "run_tests", "run_validations"]),
        "disallowed_actions": disallowed,
        "related_agents": [],
        "dependencies": [],
        "tool_access": "planning (read + write artifacts)" if is_planning else "implementation (read/write/run)",
        "test_fixtures": [f"tests/fixtures/skills/{name}.fixture.md"],
        "claude_adapter": {
            "mechanism": "skill" if "claude" in scopes else "n/a",
            "path": f".claude/skills/{name}/SKILL.md" if "claude" in scopes else None,
        },
        "codex_adapter": {
            "mechanism": "skill" if "codex" in scopes else "n/a",
            "path": f".agents/skills/{name}/SKILL.md" if "codex" in scopes else None,
        },
        "compatibility_notes": {
            "planning": "Claude planning skill; primary planning belongs to Claude.",
            "implementation": "Codex implementation skill; contains a runnable procedure.",
            "shared": "Shared: one canonical definition projected into both runtimes.",
        }[scope],
        "version": VERSION,
    }


def main() -> int:
    os.makedirs(OUT, exist_ok=True)
    agents = [build_agent(a) for a in AGENTS]
    skills = [build_skill(s) for s in SKILLS]
    # integrity: unique ids/names
    aids = [a["id"] for a in agents]
    snames = [s["name"] for s in skills]
    assert len(aids) == len(set(aids)), "dup agent id"
    assert len(snames) == len(set(snames)), "dup skill name"
    with open(os.path.join(OUT, "agents.json"), "w", encoding="utf-8") as fh:
        json.dump({"version": VERSION, "agents": agents}, fh, indent=2)
        fh.write("\n")
    with open(os.path.join(OUT, "skills.json"), "w", encoding="utf-8") as fh:
        json.dump({"version": VERSION, "skills": skills}, fh, indent=2)
        fh.write("\n")
    n_plan_a = sum(1 for a in agents if a["runtime_scope"] == ["claude"])
    n_impl_a = sum(1 for a in agents if a["runtime_scope"] == ["codex"])
    n_plan_s = sum(1 for s in skills if s["scope"] == "planning")
    n_impl_s = sum(1 for s in skills if s["scope"] == "implementation")
    n_shared_s = sum(1 for s in skills if s["scope"] == "shared")
    print(f"agents.json: {len(agents)} ({n_plan_a} planning, {n_impl_a} implementation)")
    print(f"skills.json: {len(skills)} ({n_plan_s} planning, {n_impl_s} implementation, {n_shared_s} shared)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
