-- Remove a shadowed/unused PL/pgSQL variable from the private recalculation
-- function while preserving the function body generated by the previous schema.

do $$
declare
  function_definition text;
  patched_definition text;
begin
  select pg_get_functiondef('private.recalcular_mes(smallint, smallint)'::regprocedure)
  into function_definition;

  patched_definition := replace(function_definition, E'\n  m smallint;', '');

  if patched_definition <> function_definition then
    execute patched_definition;
  end if;
end $$;
