create table if not exists public.github_integration_test (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone not null default now(),
  source text not null default 'github'
);

alter table public.github_integration_test enable row level security;
